<a href="https://colab.research.google.com/github/tvnmx/AI_nootebooks/blob/main/Meshkova_A_Workbook2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.3.1 Задание


Задача:
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [8]:
import numpy as np
arr = np.full(100, 0).reshape(10, 10)
for i in range(10):
  for j in range(10):
    if (i + j) % 2 == 0:
      arr[i][j] = 1
print(arr)

[[1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]]


1.3.2 Задание

Задача:
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [23]:
import numpy as np

arr = np.arange(5)
arr = np.tile(arr, (5, 1))

print(arr)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


1.3.3 Задание

Задача:
Создать массив 3x3x3 со случайными значениями.

In [24]:
import numpy as np

arr = np.random.random((3,3,3))
print(arr)

[[[0.35927669 0.46036853 0.62281594]
  [0.0787299  0.33689319 0.57987605]
  [0.96083615 0.68680198 0.1234955 ]]

 [[0.53025773 0.77438939 0.96694339]
  [0.45894766 0.34726448 0.4295317 ]
  [0.88670613 0.76398908 0.3591203 ]]

 [[0.89111463 0.73966236 0.14905081]
  [0.37455346 0.12546977 0.46127755]
  [0.21366982 0.12977131 0.86226855]]]


1.3.4 Задание

Задача:
Создать матрицу с 0 внутри, и 1 на границах.

In [25]:
import numpy as np

m = 5
arr = np.full(m * m, 0).reshape(m, m)
for elem in range(m):
    if elem == 0 or elem == m - 1:
        arr[elem] = np.full(m, 1)
    arr[elem][0] = 1
    arr[elem][m - 1] = 1
print(arr)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


1.3.5 Задание

Задача:
Создайте массив и отсортируйте его по убыванию.

In [27]:
import numpy as np

arr = np.random.random(5)
arr = np.sort(arr)[::-1]
print(arr)

[0.88107748 0.86385559 0.76203528 0.62675299 0.439996  ]


1.3.6 Задание

Задача:
Создайте матрицу, выведите ее форму, размер и размерность.

In [30]:
arr = np.random.random((5, 5, 5))
print(arr.shape)

(5, 5, 5)


2.3.1 Задание

Задача:
Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [33]:
import pandas as pd

a = pd.Series([1, 2, 3, 4, 5])
b = pd.Series([5, 4, 3, 2, 1])
s = sum((a - b) ** 2) ** 0.5
print(s)

6.324555320336759


2.3.2 Задание

Задача:
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных

In [43]:
import pandas as pd

link = 'https://raw.githubusercontent.com/akmand/datasets/main/iris.csv'
dataframe = pd.read_csv(link)
dataframe.head(5)
dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0                5.1             3.5              1.4             0.2   
1                4.9             3.0              1.4             0.2   
2                4.7             3.2              1.3             0.2   
3                4.6             3.1              1.5             0.2   
4                5.0             3.6              1.4             0.2   
..               ...             ...              ...             ...   
145              6.7             3.0              5.2             2.3   
146              6.3             2.5              5.0             1.9   
147              6.5             3.0              5.2             2.0   
148              6.2             3.4              5.4             2.3   
149              5.9             3.0              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

2.3.3 Задание

Задача:
Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.

In [49]:
import pandas as pd

link = 'https://raw.githubusercontent.com/akmand/datasets/main/iris.csv'
dataframe = pd.read_csv(link)
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()
dataframe.iloc[1:4]
dataframe[dataframe['species'] == 'virginica'].head(2)

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
100              6.3             3.3              6.0             2.5   
101              5.8             2.7              5.1             1.9   

       species  
100  virginica  
101  virginica

3.3.2 Задание

Задача:
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [53]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

link = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
dataframe = pd.read_csv(link)

scaler = MinMaxScaler()
dataframe["sepal_length_cm_2"] = scaler.fit_transform(dataframe[["sepal_length_cm"]])

scaler = StandardScaler()
dataframe["sepal_width_cm_2"] = scaler.fit_transform(dataframe[["sepal_width_cm"]])

print(dataframe)


     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0                5.1             3.5              1.4             0.2   
1                4.9             3.0              1.4             0.2   
2                4.7             3.2              1.3             0.2   
3                4.6             3.1              1.5             0.2   
4                5.0             3.6              1.4             0.2   
..               ...             ...              ...             ...   
145              6.7             3.0              5.2             2.3   
146              6.3             2.5              5.0             1.9   
147              6.5             3.0              5.2             2.0   
148              6.2             3.4              5.4             2.3   
149              5.9             3.0              5.1             1.8   

       species  sepal_length_cm_2  sepal_width_cm_2  
0       setosa           0.222222          1.032057  
1       setosa 